

==== 所有可用的 clone 命令 ====
git clone git@github.com:daoyuly/5-Day-AI-Agents-Intensive-Course-with-Google.git
git clone git@github.com:daoyuly/AWorld.git
git clone git@github.com:daoyuly/Advanced-Prompt-Generator.git
git clone https://github.com/simular-ai/Agent-S.git
git clone https://github.com/reworkd/AgentGPT.git
git clone https://github.com/open-mmlab/Amphion.git
git clone git@github.com:Significant-Gravitas/AutoGPT.git
git clone https://github.com/elder-plinius/AutoStoryGen.git
git clone https://github.com/HqWu-HITCS/Awesome-Chinese-LLM.git
git clone git@github.com:daoyuly/BMAD-METHOD.git
git clone git@github.com:daoyuly/BettaFish.git
git clone https://github.com/elder-plinius/CL4R1T4S.git
git clone https://github.com/qdhenry/Claude-Command-Suite.git
git clone https://github.com/ZTE-AICloud/Co-Sight.git
git clone https://github.com/stanford-futuredata/ColBERT.git
git clone https://github.com/666ghj/DeepSearchAgent-Demo.git
git clone https://github.com/melih-unsal/DemoGPT.git
git clone git@github.com:daoyuly/Devyan.git
git clone git@github.com:daoyuly/DocsGPT.git
git clone https://github.com/akshaybahadur21/Emojinator.git
git clone git@github.com:daoyuly/EverMemOS.git
git clone https://github.com/FlowiseAI/Flowise.git
git clone https://github.com/Morizeyao/GPT2-Chinese.git
git clone https://github.com/yangjianxin1/GPT2-chitchat.git
git clone git@github.com:daoyuly/GPTs.git
git clone https://github.com/LeiLiLab/InfiniSST.git
git clone git@github.com:daoyuly/IntelliQ.git
git clone https://github.com/zjunlp/KnowLM.git
git clone git@github.com:daoyuly/Kode.git
git clone https://github.com/pengxiao-song/LaWGPT.git
git clone https://github.com/wxai-space/LightAgent.git
git clone https://github.com/wbbeyourself/MAC-SQL.git
git clone https://github.com/guangyaooo/MLTemplate.git
git clone https://github.com/1Panel-dev/MaxKB.git
git clone git@github.com:GibsonAI/Memori.git
git clone https://github.com/geekan/MetaGPT.git
git clone git@github.com:daoyuly/MoonshotAI-Cookbook.git
git clone git@github.com:daoyuly/MultiAgentPPT.git
git clone https://github.com/simular-ai/OpenACI.git
git clone git@github.com:daoyuly/OpenDevin.git
git clone git@github.com:daoyuly/OpenManus.git
git clone git@github.com:daoyuly/QAnything.git
git clone https://github.com/QwenLM/Qwen-Agent.git
git clone git@github.com:daoyuly/RepoAgent.git
git clone git@github.com:daoyuly/Skywork.git
git clone git@github.com:daoyuly/Thinking-Claude.git
git clone https://github.com/sansan0/TrendRadar.git
git clone git@github.com:daoyuly/UnilmChatchitRobot.git
git clone https://github.com/int2520yl/Veriminder.git
git clone git@github.com:daoyuly/VideoAgent.git
git clone https://github.com/Alibaba-NLP/WebAgent.git
git clone https://github.com/duguiming111/Wheels-of-Machine-Learning-Algorithms.git
git clone git@github.com:daoyuly/actual.git
git clone https://github.com/relari-ai/agent-examples.git
git clone git@github.com:daoyuly/agent-rules.git
git clone git@github.com:daoyuly/agentic-design-patterns.git
git clone https://github.com/huangjia2019/ai-agents.git
git clone https://github.com/Leniolabs/ai-data-dashboard.git
git clone https://github.com/virattt/ai-hedge-fund.git
git clone git@github.com:daoyuly/ai-pdf-chatbot-langchain.git
git clone https://github.com/amazon-science/auto-cot.git
git clone git@github.com:daoyuly/autogen.git
git clone https://github.com/ucinlp/autoprompt.git
git clone git@github.com:daoyuly/awesome-llm-apps.git
git clone git@github.com:daoyuly/browser-use.git
git clone git@github.com:daoyuly/cc.git
git clone https://github.com/celery/celery.git
git clone https://github.com/getAsterisk/claudia.git
git clone https://github.com/prompt-engineering/click-prompt
git clone https://github.com/cline/cline.git
git clone https://github.com/xingyaoww/code-act.git
git clone https://github.com/codefuse-ai/codefuse-chatbot.git
git clone https://github.com/openai/codex.git
git clone https://github.com/coze-dev/coze-studio.git
git clone git@github.com:daoyuly/crewAI-examples.git
git clone https://github.com/crewAIInc/crewAI.git
git clone git@github.com:daoyuly/deepagents.git
git clone https://github.com/bytedance/deer-flow.git
git clone https://github.com/hanfangyuan4396/dify-on-wechat.git
git clone https://github.com/langgenius/dify.git
git clone git@github.com:daoyuly/dyad.git
git clone https://github.com/antgroup/echomimic_v2.git
git clone https://github.com/rany2/edge-tts.git
git clone git@github.com:daoyuly/eko.git
git clone https://github.com/fastapi/fastapi.git
git clone https://github.com/jlowin/fastmcp.git
git clone https://github.com/google-gemini/gemini-cli.git
git clone https://github.com/google-gemini/gemini-fullstack-langgraph-quickstart.git
git clone https://github.com/ahmedkhaleel2004/gitdiagram.git
git clone git@github.com:daoyuly/goose.git
git clone https://github.com/openai/gpt-2.git
git clone https://github.com/builderio/gpt-crawler
git clone https://github.com/ainoya/gpt-looker.git
git clone https://github.com/assafelovic/gpt-researcher.git
git clone https://github.com/imcaspar/gpt2-ml.git
git clone git@github.com:arcstep/illufly.git
git clone git@github.com:daoyuly/illufly.git
git clone https://github.com/khoj-ai/khoj.git
git clone https://github.com/Kilo-Org/kilocode.git
git clone https://github.com/MoonshotAI/kimi-cli.git
git clone https://github.com/Lesterpaintstheworld/kinos.git
git clone https://github.com/MoonshotAI/kosong.git
git clone https://github.com/Dawanfe/langmanus-web.git
git clone git@github.com:daoyuly/langmanus.git
git clone https://github.com/WisdomShell/llama_cpp_for_codeshell.git
git clone git@github.com:daoyuly/lobe-chat.git
git clone https://github.com/whit3rabbit/manus-open.git
git clone https://github.com/lastmile-ai/mcp-agent.git
git clone https://github.com/mem0ai/mem0.git
git clone https://github.com/karpathy/minGPT.git
git clone git@github.com:daoyuly/mini-swe-agent.git
git clone https://github.com/qiufengqijun/mini_qwen.git
git clone https://github.com/n8n-io/n8n.git
git clone https://github.com/karpathy/nanoGPT.git
git clone https://github.com/karpathy/nanochat.git
git clone https://github.com/langchain-ai/open_deep_research.git
git clone https://github.com/openagents-org/openagents.git
git clone https://github.com/openai/openai-agents-js.git
git clone https://github.com/openai/openai-agents-python.git
git clone https://github.com/openai/openai-cookbook.git
git clone git@github.com:daoyuly/openai-cs-agents-demo.git
git clone https://github.com/camel-ai/owl.git
git clone https://github.com/potpie-ai/potpie.git
git clone https://github.com/allweonedev/presentation-ai.git
git clone https://github.com/character-ai/prompt-poet.git
git clone git@github.com:daoyuly/pydial3.git
git clone https://github.com/huggingface/smolagents.git
git clone https://github.com/NVlabs/stylegan.git
git clone https://github.com/kortix-ai/suna.git
git clone https://github.com/daoyuly/system-prompts-and-models-of-ai-tools.git
git clone https://github.com/vanna-ai/vanna.git
git clone https://github.com/TencentCloudADP/youtu-agent.git
